### ISSUE TITLE
ReadMe update

### ISSUE THREAD

**Issue by hhzl** [mumez/SIXX#1]
Could you please provide load instructions for Pharo 4.0 and Squeak 4.6 / 5 in the ReadMe file?

And a reference to the Cuis version if it is available.

And http://www.mars.dti.ne.jp/~umejava/smalltalk/sixx/index.html should have a link to this repository from the 'what is new' section.

http://pharo.gemtalksystems.com/book/PharoTools/SIXX/ refers to http://www.mars.dti.ne.jp/~umejava/smalltalk/sixx/index.html

**Comment by mumez** [comment]
Thank you for reminding me. I should update some old documents. First I'll check if SIXX is compatible with the latest Pharo 4.0 / Squeak 5.0. 
And Cuis version is still not available! I think the porting would be easy. Please stay tuned.

**Comment by hhzl** [comment]
I realize that FileTree is preinstalled in Pharo 3.0 and 4.0. So
loading SIXX is straightforward.

https://github.com/dalehenrich/filetree

I forked the repository, did

```
  git clone https://github.com/hhzl/SIXX.git
```

And then used the Monticello browser to add the local repository.

Loading issue see #2

**Comment by mumez** [comment]
Now I've updated README.
https://github.com/mumez/SIXX/commit/8b856641787db1ae93d7e1d946b039ccba98ad5c

Also http://www.mars.dti.ne.jp/~umejava/smalltalk/sixx/index.html now refers to the GitHub repository.
