### ISSUE TITLE
Show CI and test status on github page

### ISSUE THREAD

**Issue by sdasda7777** [mumez/SIXX#13]
Hi, would it be possible to show CI and test status on the github page?

It would make everyone aware of the state of the project from the first sight - I hope you can agree that would be a good thing.

**Comment by mumez** [comment]
Thank you for your suggestion.
I will try adding GitHub actions for CI soon!

**Comment by mumez** [comment]
Now I've added the CI config.
https://github.com/mumez/SIXX/pull/15

You can see the status badge on [README](https://github.com/mumez/SIXX/blob/master/README.md).  Works great.

**Comment by sdasda7777** [comment]
Very nice, thanks!
