### ISSUE TITLE
Load problem in Pharo 4.0

### ISSUE THREAD

**Issue by hhzl** [mumez/SIXX#2]
![sixx_in_pharo4 0_load_problem_screenshot from 2015-08-24 08 06 12](https://cloud.githubusercontent.com/assets/1112023/9433758/1de51200-4a37-11e5-86c2-cf8e265fabe9.png)

**Comment by hhzl** [comment]
ContextPart and MethodContext classes replaced with Context
https://github.com/pharo-project/pharo-changelogs/blob/master/Pharo40ChangeLogs.md
(ContextPart and MethodContext classes have been merged into Context class)

**Comment by hhzl** [comment]
When doing

```
Context variableSubclass: #ContextPart
    instanceVariableNames: ''
    classVariableNames: ''
    category: 'Kernel-Methods'
```

before loading then it loads fine.

![sixx_tests_on_pharo4 0_screenshot from 2015-08-24 20 57 59](https://cloud.githubusercontent.com/assets/1112023/9449435/dd67e722-4aa2-11e5-99e2-0e978944773f.png)

But 

![sixx_on_pharo_4 0_failed_tests_screenshot from 2015-08-24 20 59 08](https://cloud.githubusercontent.com/assets/1112023/9449465/079b9854-4aa3-11e5-895a-f8c9fe527069.png)

**Comment by mumez** [comment]
Thank you for the report. I'll look into the ContextPart issue.

**Comment by mumez** [comment]
Moved ContextPart extension methods to Context. Now all tests are green in Pharo 4.0.
https://github.com/mumez/SIXX/commit/02529e97f1effcbe58e817d9bda1cd0ee5380bcd

**Comment by hhzl** [comment]
SIXX tests are fine in [Pharo 4.0](https://github.com/pharo-project). Thank you!

![sixx_pharo_4 0_tests_2015-08-28 09 38 07](https://cloud.githubusercontent.com/assets/1112023/9541474/a138c9b0-4d68-11e5-91d1-93d28fb78b24.png)
